const CONSTANTS = {}

CONSTANTS.ROLES = {
  FIRST_RESPONDER : "FIRST RESPONDER",
  MEDICAL_PROFESSIONAL : "MEDICAL PROFESSIONAL",
  PATIENT : "PATIENT"
}

CONSTANTS.SERVER_URL = "http://localhost:3000"

module.exports = CONSTANTS;